version: '3'
services:
  designer:
    image: vlingo/xoom-designer:latest
    container_name: xoom-designer
    ports:
      - 19090:19090
    environment:
      VLINGO_XOOM_DESIGNER_SERVER_PORT: 19090
      VLINGO_XOOM_DESIGNER_ENV: "CONTAINER"

  schemata:
    image: vlingo/xoom-schemata:latest
    container_name: xoom-schemata
    ports:
      - 9019:9019
    environment:
      XOOM_ENV: "dev"